# Generated by Django 2.1.7 on 2019-03-18 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(help_text='Introduce only format images .png , .mp4 , .tiff or .bmp ', upload_to='images/imagenes/', validators=[django.core.validators.FileExtensionValidator(['BMP', 'PNG', 'TIFF', 'MP4'], 'The image was not uploaded:invalid format')], verbose_name='file')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Files2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen2', models.FileField(help_text='Introduce only format images .png , .mp4 , .tiff or .bmp ', upload_to='images/imagenes2/', validators=[django.core.validators.FileExtensionValidator(['BMP', 'PNG', 'TIFF', 'MP4'], 'The image was not uploaded:invalid format')], verbose_name='file2')),
                ('timestamp2', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
