# Generated by Django 2.1.7 on 2019-03-18 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen3', models.FileField(help_text='Introduce only format images .png , .tif , .avi , .wmv , .mp4 , .tiff or .bmp ', upload_to='images/imagenes3/', validators=[django.core.validators.FileExtensionValidator(['BMP', 'PNG', 'TIF', 'TIFF', 'MP4', 'AVI', 'MOV', 'WMV'], 'The image was not uploaded:invalid format')], verbose_name='file3')),
                ('timestamp3', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File3',
                'verbose_name_plural': 'Files3',
            },
        ),
        migrations.AlterModelOptions(
            name='files2',
            options={'verbose_name': 'File2', 'verbose_name_plural': 'Files2'},
        ),
        migrations.AlterField(
            model_name='files',
            name='imagen',
            field=models.FileField(help_text='Introduce only format images .png , .tif , .avi , .wmv , .mp4 , .tiff or .bmp ', upload_to='images/imagenes/', validators=[django.core.validators.FileExtensionValidator(['BMP', 'PNG', 'TIF', 'TIFF', 'MP4', 'AVI', 'MOV', 'WMV'], 'The image was not uploaded:invalid format')], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='files2',
            name='imagen2',
            field=models.FileField(help_text='Introduce only format images .png , .tif , .avi , .wmv , .mp4 , .tiff or .bmp ', upload_to='images/imagenes2/', validators=[django.core.validators.FileExtensionValidator(['BMP', 'PNG', 'TIF', 'TIFF', 'MP4', 'AVI', 'MOV', 'WMV'], 'The image was not uploaded:invalid format')], verbose_name='file2'),
        ),
    ]
